import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "../ui/fonts";
import { Providers } from "../ui/provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Layouts from "../ui/layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <AntdRegistry>
            <Layouts>
              {children}
            </Layouts>
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
